[my_chat]
url = "https://t.me/PopOs_en"

[wants_to_join]
agreement = "Hi and welcome to https://t.me/PopOs_en! We hope you'll have a great time. Please mind these 3 rules:\n1) Be respectful: address people as you would address them in a non-digital setting.\n2) Do your research: before asking questions, search this chat for answers, as well as https://support.system76.com/, https://www.reddit.com/r/pop_os/ and your favorite web engine.\n3) Be relevant: this chat is primarily about Pop!_OS, one of the few distributions that really cares about your hardware, user experience and productivity. We tolerate broader themes in the range of Linux, software and computers, but please try to minimize offtopic adventures.\nFinally, notice that the chat is bridged to Matrix (another messaging service). \n\nNow use the button below to confirm you agree!"
ok = "I agree, let me in"

[commands]
help = "This simple bot lets you define 'routes' of the shape 'origin:destination' such that the bot will post join requests from users from 'origin' to 'destination'.\n\nThe bot must be a member of BOTH. Also be aware that this is a 1-1 relation -- the bot routes each origin to EXACTLY ONE destination."

[has_joined]
destination = "Thanks for adding me to this monitoring chat. If that's not done already, add me to the chat whose join requests you want me to monitor. They will be notified here:"
not_destination = "Thanks for adding me to this group chat. If that's not done already, add me to the monitoring chat. Join requests made here will be notified to the monitoring chat."

[checking_routing]
destination = "I am already routing requests from a chat to this monitoring chat. Use /route with an optional <chat_id> argument from the chat receiving join requests to change the destination."
not_destination = "I am already routing join requests to a monitoring chat. Use /route with an optional <chat_id> argument from here to change the destination."
not_routing = "I am not routing any join requests. Use /route with an optional <chat_id> argument in a chat receiving join requests to add a monitoring chat. Without argument, the monitoring chat = the chat where /route is issued."

[resetting_routing]
disabled = "All routing from this chat have been disabled. Use /route with an optional <chat_id> argument to start over."